name: action
description: "Action: Organize your life!"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  collection: ^1.19.0
  core_y:
    git:
      url: https://github.com/Yogi-7y/Project-Y
      path: packages/core
      ref: result
  envied: ^1.0.0
  figma_squircle_updated: ^1.0.1
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  flutter_native_splash: ^2.4.4
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.2
  google_sign_in: ^6.2.2
  intl: ^0.20.1
  just_audio: ^0.9.43
  meta: ^1.15.0
  rxdart: ^0.28.0
  shimmer: ^3.0.0
  smart_textfield:
    git:
      url: https://github.com/Yogi7y/smart-text-field
      ref: searchable-dropdown
  stack_trace: ^1.12.0
  supabase_flutter: ^2.8.2
  svg_flutter: ^0.0.1

dev_dependencies:
  build_runner: ^2.4.14
  clock: ^1.1.1
  envied_generator: ^1.0.0
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter
  icon_font_generator: ^4.0.0
  lints_y:
    git:
      url: https://github.com/Yogi-7y/Project-Y
      path: packages/lints
      ref: result
  mock_supabase_http_client: ^0.0.3+1
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_variable.ttf
    - family: AppIcons
      fonts:
        - asset: assets/fonts/app_icons.ttf

  assets:
    - assets/brand/
    - assets/sounds/
    - assets/fonts/
