name: action
description: "Action: Organize your life!"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  auto_route: ^9.2.2
  collection: ^1.19.0
  core_y: ^0.3.1
  envied: ^1.0.0
  figma_squircle_updated: ^1.0.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.16
  google_sign_in: ^6.2.2
  intl: ^0.20.1
  rxdart: ^0.28.0
  smart_textfield: ^1.1.0
  stack_trace: ^1.12.0
  supabase_flutter: ^2.8.2
  svg_flutter: ^0.0.1

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.14
  clock: ^1.1.1
  envied_generator: ^1.0.0
  flutter_test:
    sdk: flutter
  lints_y:
    git:
      url: https://github.com/Yogi-7y/Project-Y
      path: packages/lints
      ref: main
  meta: ^1.15.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_variable.ttf

  assets:
    - assets/icons/
