/// Flutter icons MyFlutterApp
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';

  static const xmark = IconData(0xe800, fontFamily: _kFontFam);
  static const userOutlined = IconData(0xe801, fontFamily: _kFontFam);
  static const tagOutlined = IconData(0xe802, fontFamily: _kFontFam);
  static const sendAlt2 = IconData(0xe803, fontFamily: _kFontFam);
  static const search = IconData(0xe804, fontFamily: _kFontFam);
  static const resources = IconData(0xe805, fontFamily: _kFontFam);
  static const plusOutlined = IconData(0xe806, fontFamily: _kFontFam);
  static const loaderOutlined = IconData(0xe807, fontFamily: _kFontFam);
  static const houseSmile = IconData(0xe808, fontFamily: _kFontFam);
  static const hammerOutlined = IconData(0xe809, fontFamily: _kFontFam);
  static const forwardStep = IconData(0xe80a, fontFamily: _kFontFam);
  static const clockOutlined = IconData(0xe80b, fontFamily: _kFontFam);
  static const circle = IconData(0xe80c, fontFamily: _kFontFam);
  static const circleDashed = IconData(0xe80d, fontFamily: _kFontFam);
  static const circleCheck = IconData(0xe80e, fontFamily: _kFontFam);
  static const chevronLeft = IconData(0xe80f, fontFamily: _kFontFam);
  static const chevronDown = IconData(0xe810, fontFamily: _kFontFam);
  static const calendarOutlined = IconData(0xe811, fontFamily: _kFontFam);
  static const calendarLinesOutlined = IconData(0xe812, fontFamily: _kFontFam);
  static const bookmarkAddOutlined = IconData(0xe813, fontFamily: _kFontFam);
  static const area = IconData(0xe814, fontFamily: _kFontFam);
  static const addTaskOutlined = IconData(0xe815, fontFamily: _kFontFam);
  static const check = IconData(0xe816, fontFamily: _kFontFam);
}
